#!/bin/sh
# DNF Configuration
sudo echo """
fastestmirror=True
max_parallel_downloads=10
defaultyes=True
keepcache=True
""" | sudo tee -a /etc/dnf/dnf.conf
sudo dnf clean dbcache
sudo dnf update
## Enable RPM Fusion
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
