#!/bin/sh
# DNF Configuration
sudo echo """
fastestmirror=True
max_parallel_downloads=10
defaultyes=True
keepcache=True
""" | sudo tee -a /etc/dnf/dnf.conf
sudo dnf clean dbcache
sudo dnf update
## Flathub
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
## Enable RPM Fusion
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
## Install Media Codecs
sudo dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
sudo dnf groupupdate sound-and-video
